/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace */
        get: operations["get_workspace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Conversation */
        get: operations["get_latest_conversation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/voice/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Voice */
        post: operations["start_voice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/voice/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Voice */
        get: operations["get_voice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/voice/{session_id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End Voice */
        post: operations["end_voice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MoneyFact */
        MoneyFact: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Amount Paise */
            amount_paise?: number | null;
            /** Min Amount Paise */
            min_amount_paise?: number | null;
            /** Max Amount Paise */
            max_amount_paise?: number | null;
            /** Usable Amount Paise */
            usable_amount_paise?: number | null;
            /**
             * Restricted
             * @default false
             */
            restricted: boolean;
            /** Due Date */
            due_date?: string | null;
            /** Recurring Day Of Month */
            recurring_day_of_month?: number | null;
            /**
             * Certainty
             * @default unknown
             * @enum {string}
             */
            certainty: "confirmed" | "estimated" | "uncertain" | "unknown";
        };
        /** PlanEvent */
        PlanEvent: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Label */
            label: string;
            /** Change Paise */
            change_paise: number;
            /** Balance Paise */
            balance_paise: number;
        };
        /** PlanSummary */
        PlanSummary: {
            /**
             * Dated Income Paise
             * @default 0
             */
            dated_income_paise: number;
            /**
             * Dated Outgoings Paise
             * @default 0
             */
            dated_outgoings_paise: number;
            /** Projected Closing Paise */
            projected_closing_paise?: number | null;
            /** Lowest Balance Paise */
            lowest_balance_paise?: number | null;
            /** First Shortfall Date */
            first_shortfall_date?: string | null;
            /**
             * Unplanned Fact Count
             * @default 0
             */
            unplanned_fact_count: number;
            /**
             * Uncertain Income Paise
             * @default 0
             */
            uncertain_income_paise: number;
            /**
             * Uncertain Outgoings Paise
             * @default 0
             */
            uncertain_outgoings_paise: number;
            /** Conditional Closing Paise */
            conditional_closing_paise?: number | null;
        };
        /** StartVoice */
        StartVoice: {
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /**
             * Conversation Mode
             * @default returning
             * @enum {string}
             */
            conversation_mode: "new" | "returning";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VoiceConnection */
        VoiceConnection: {
            /** Session Id */
            session_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "starting" | "active" | "ended" | "failed";
            /** Error */
            error?: string | null;
            /** Error Code */
            error_code?: string | null;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
            /**
             * Activity
             * @default connecting
             * @enum {string}
             */
            activity: "connecting" | "thinking" | "speaking" | "listening" | "ended" | "failed";
            /** Room Url */
            room_url: string;
            /** Token */
            token: string;
            /** Expires At */
            expires_at: number;
        };
        /** VoiceState */
        VoiceState: {
            /** Session Id */
            session_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "starting" | "active" | "ended" | "failed";
            /** Error */
            error?: string | null;
            /** Error Code */
            error_code?: string | null;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
            /**
             * Activity
             * @default connecting
             * @enum {string}
             */
            activity: "connecting" | "thinking" | "speaking" | "listening" | "ended" | "failed";
        };
        /** Workspace */
        Workspace: {
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /**
             * Currency
             * @default INR
             * @constant
             */
            currency: "INR";
            /**
             * Window Start
             * Format: date
             */
            window_start: string;
            /**
             * Window End Exclusive
             * Format: date
             */
            window_end_exclusive: string;
            /** Opening Cash Paise */
            opening_cash_paise?: number | null;
            /** Opening Cash */
            opening_cash?: components["schemas"]["MoneyFact"][];
            /** Income */
            income?: components["schemas"]["MoneyFact"][];
            /** Commitments */
            commitments?: components["schemas"]["MoneyFact"][];
            /** Expenses */
            expenses?: components["schemas"]["MoneyFact"][];
            /**
             * Plan Status
             * @default not_started
             * @enum {string}
             */
            plan_status: "not_started" | "building" | "ready";
            summary?: components["schemas"]["PlanSummary"];
            /** Timeline */
            timeline?: components["schemas"]["PlanEvent"][];
            /**
             * Voice Available
             * @default false
             */
            voice_available: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_workspace: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_conversation: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    } | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_voice: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartVoice"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceConnection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_voice: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-user-id"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_voice: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-user-id"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
